#! /bin/sh

#####
# Variables
#####

README='README.md'
AUTO_GEN_STRING="<!-- DO NOT EDIT THIS FILE - AUTO-GENERATED -->"

#####
# Functions
#####

appendFileToReadme () {
  if [ ! -z $2 ] 
    then echo "## $2\n" >> $README 
  fi
  
  cat $1 >> $README
}

listDirectories() {
  ls -d $1*/ 2> /dev/null
}

makeIndexFile() {
  echo "building Index for $1"
  echo "## Index \n" > $1/_index.md

  ls $1 --ignore=_* | while read entry
    do
      FILE_PATH=`echo "$entry" | sed -e "s|$1|.|"`
      NAME=`echo $FILE_PATH | sed -e "s|\..*||"`
      
      # Replace spaces to URL encoded
      FILE_PATH=`echo "$entry" | sed -e "s| |%20|"`
      
      echo "- [$NAME](./$FILE_PATH)" >> $1/_index.md
  done
}

makeIndexes() {
  makeIndexFile $1
    
  listDirectories $1 | while read x
  do
    makeIndexes $x;
  done
}

#####
# Setup
#####

echo "# $README \n" > $README

#####
# Index
#####

makeIndexes 'notes/'

exit 1;

#####
# Tree
#####

# Create tree

sh ./scripts/tree.sh

# Append Tree

## embed in code block
echo '```' | cat - ./notes/_tree.md > temp
echo '```' >> temp

## replace generated tree root
sed -i 's|/notes|.|' temp
mv -f temp ./notes/_tree.md

appendFileToReadme ./notes/_tree.md "Tree"